jubatus/server/common/mprpc/rpc_client_test.cpp
This will fix https://github.com/jubatus/jubatus/issues/885 and https://github.com/jubatus/jubatus/issues/886.
=> Fix test for rpc client

tools/jenerator/src/go.ml
* Use "ID" instead of "Id" for more go-ishness
* Update copyright  year and remove unnecessary comment
=> Go client tiny amendments

config/classifier/nn.json
Example config for NN-based classifier introduced in https://github.com/jubatus/jubatus_core/pull/83.
=> add example config for NN-based classifier

tools/jenerator/src/OMakefile, tools/jenerator/src/config.ml, tools/jenerator/src/go.ml, tools/jenerator/src/main.ml
We implemented new client for [golang](http://golang.org/). #870
=> Golang client

jubatus/client/nearest_neighbor_client.hpp, jubatus/client/nearest_neighbor_types.hpp, jubatus/server/server/nearest_neighbor.idl, jubatus/server/server/nearest_neighbor_impl.cpp, jubatus/server/server/nearest_neighbor_proxy.cpp, jubatus/server/server/nearest_neighbor_serv.cpp, jubatus/server/server/nearest_neighbor_serv.hpp
Refs: https://github.com/jubatus/jubatus_core/issues/58
Depends on: https://github.com/jubatus/jubatus_core/pull/101
=> implement get_all_rows API in NN

tools/jenerator/src/go.ml
I forgot to push modification which append common functions for go client generation.
=> golang-client: add common function

jubatus/server/server/anomaly.idl, tools/jenerator/src/go.ml
https://github.com/jubatus/jubatus/issues/906
=> Replace "Preferred Infrastructure" with "Preferred Networks."

config/bandit/epsilon_greedy.json, config/bandit/exp3.json, config/bandit/softmax.json, config/bandit/ucb1.json, jubatus/client/bandit_client.hpp, jubatus/client/bandit_types.hpp, jubatus/server/server/bandit.idl, jubatus/server/server/bandit_impl.cpp, jubatus/server/server/bandit_proxy.cpp, jubatus/server/server/bandit_serv.cpp, jubatus/server/server/bandit_serv.hpp, jubatus/server/server/bandit_types.hpp, jubatus/server/server/wscript
Online optimization algorithm `Bandit` is implemented.
It includes 4 patterns of bandit algorithms.
=> New feature: bandit algorithm

jubatus/server/server/anomaly_proxy.cpp, jubatus/server/server/bandit_proxy.cpp, jubatus/server/server/burst_proxy.cpp, jubatus/server/server/classifier_proxy.cpp, jubatus/server/server/clustering_proxy.cpp, jubatus/server/server/graph_proxy.cpp, jubatus/server/server/nearest_neighbor_proxy.cpp, jubatus/server/server/recommender_proxy.cpp, jubatus/server/server/regression_proxy.cpp, jubatus/server/server/stat_proxy.cpp, tools/jenerator/src/cpp.ml
Proxy now exits with the status code.
=> fix proxy to return exit code (fix #928)

jubatus/server/framework/server_util.hpp
=> remove unused method from header (fix #917)

client_test/wscript, config/wscript, jubatus/client/common/wscript, jubatus/client/wscript, jubatus/server/cmd/wscript, jubatus/server/server/wscript, jubatus/server/third_party/cmdline/wscript, jubatus/server/third_party/wscript, jubatus/server/wscript, jubatus/wscript, plugin/wscript
https://github.com/jubatus/jubatus/issues/924
=> Add "# -*- python -*-" to wscripts for eamcs.

jubatus/server/server/burst.idl, jubatus/server/server/burst_serv.cpp, jubatus/server/server/burst_serv.hpp
=> add clear API to burst engine (fix #919)

jubatus/server/server/anomaly_serv.cpp
Remove duplicate using declarations.
=> Remove duplicate using declarations.

jubatus/server/framework/server_helper.cpp
=> fix typo in log message

jubatus/server/server/nearest_neighbor_serv.cpp
=> Fix for cpplint.

jubatus/server/common/membership.cpp, jubatus/server/common/membership.hpp
=> Removed "force_exit" from "register_active"

jubatus/server/common/signals.cpp
Fixes https://github.com/jubatus/jubatus/issues/956.
=> Add default action on SIGTERM/SIGINT

jubatus/server/cmd/jubaconv.cpp, jubatus/server/cmd/wscript
Make jubaconv to use dynamic fv_converter.
=> Make jubaconv to use dynamic fv_converter.

jubatus/server/framework/mixer/linear_mixer.cpp
=> Stop mixer immediately if MIX protocol version mismatch detected

jubatus/server/common/zk.cpp
=> print ZooKeeper host on reconnection (fix #913)

config/bandit/epsilon_greedy.json, config/bandit/exp3.json, config/bandit/softmax.json, config/bandit/ucb1.json, jubatus/server/server/bandit.idl
related issues: https://github.com/jubatus/jubatus_core/issues/125, https://github.com/jubatus/jubatus_core/pull/133
=> Add assume_unrewarded option

jubatus/server/cmd/jubaconv.cpp
=> fix cpplint (refs #963)

jubatus/server/server/classifier.idl, jubatus/server/server/classifier_proxy.cpp
=> use broadcast distribution logic for classifier set_label API (fix #850)

jubatus/server/server/anomaly.idl, jubatus/server/server/anomaly_proxy.cpp
=> anomaly get_all_rows API must be distributed randomly (fix #974)

config/anomaly/light_lof_combinational_feature.json, config/classifier/arow_combinational_feature.json, config/clustering/kmeans_combinational_feature.json, config/nearest_neighbor/lsh_combinational_feature.json, config/recommender/lsh_combinational_feature.json, config/regression/pa_combinational_feature.json
I have added config files using combinational feature.
This PR is related to #953.
=> add combinational config files

jubatus/server/server/nearest_neighbor_serv.cpp, jubatus/server/server/recommender_serv.cpp
related issue: https://github.com/jubatus/jubatus/issues/990
=> Fix macro name

jubatus/server/framework/mixer/broadcast_mixer.hpp, jubatus/server/framework/mixer/push_mixer.cpp, jubatus/server/framework/mixer/push_mixer_test.cpp, jubatus/server/framework/mixer/random_mixer.hpp
fixes https://github.com/jubatus/jubatus/issues/915.
=> Fix skip mixer to select different peers

jubatus/server/server/nearest_neighbor_serv.cpp
related issue: https://github.com/jubatus/jubatus/issues/984
=> Print config on startup of nearest_neighbor

jubatus/server/framework/mixer/push_mixer_test_util.hpp, jubatus/server/framework/mixer/skip_mixer_test.cpp, jubatus/server/framework/mixer/wscript
Add test for skip_mixer.
Refs #995
=> add test for skip_mixer

jubatus/server/common/membership.cpp, jubatus/server/framework/proxy_common.cpp, jubatus/server/framework/server_helper.cpp
=> fix push_cleanup location (fix #967)

jubatus/server/server/classifier.idl, jubatus/server/server/classifier_impl.cpp, jubatus/server/server/classifier_proxy.cpp, jubatus/server/server/classifier_types.hpp
fix #968 
blocked by https://github.com/jubatus/jubatus_core/pull/144
=> remove giant lock on classifier (fix #968)

jubatus/server/common/signals.cpp
fixes https://github.com/jubatus/jubatus/issues/988
=> Stop sigwait thread on SIGTERM/SIGINT

tools/packaging/rpm/package-prebuild, tools/packaging/rpm/rpmbuild/jubadump/SPECS/jubadump.spec.in, tools/packaging/rpm/rpmbuild/jubatus-core/SPECS/jubatus-core.spec.in, tools/packaging/rpm/rpmbuild/jubatus-msgpack-rpc/SPECS/jubatus-msgpack-rpc.spec.in, tools/packaging/rpm/rpmbuild/jubatus/SPECS/jubatus.spec.in, tools/packaging/rpm/rpmbuild/mecab-ipadic/SPECS/mecab-ipadic.spec.in
=> add strict version requirements

jubatus/server/framework/server_base.cpp
Fix https://github.com/jubatus/jubatus/issues/1012.
=> Fix load file path

man/en/jubadump.1, man/ja/jubadump.1
Regenerated.
Please merge after https://github.com/jubatus/website/pull/203.
=> update jubadump man pages

client_test/anomaly_test.cpp, client_test/classifier_test.cpp, client_test/clustering_test.cpp, client_test/graph_test.cpp, client_test/nearest_neighbor_test.cpp, client_test/recommender_test.cpp, client_test/regression_test.cpp, client_test/stat_test.cpp, jubatus/client/common/client.hpp
related to: https://github.com/jubatus/jubatus/pull/971
=> Fix return type of save method in client

jubatus/server/server/anomaly.idl, jubatus/server/server/anomaly_client.hpp, jubatus/server/server/anomaly_impl.cpp, jubatus/server/server/anomaly_proxy.cpp, jubatus/server/server/anomaly_types.hpp, jubatus/server/server/classifier.idl, jubatus/server/server/classifier_impl.cpp, jubatus/server/server/classifier_proxy.cpp, jubatus/server/server/classifier_types.hpp
FIxes https://github.com/jubatus/jubatus/issues/1002, https://github.com/jubatus/jubatus/issues/1003
=> Fix merge methods

jubatus/server/framework/proxy.cpp, jubatus/server/framework/proxy.hpp
ralated issue: https://github.com/jubatus/jubatus/issues/985
=> Implement the expected exception behavior of JubaProxy

jubatus/server/server/classifier_serv.cpp
=> Fix classifier to update update_count

config/recommender/inverted_index_unlearn_lru.json
Refs https://github.com/jubatus/jubatus_core/pull/120
=> add example config file for inverted_index with unlearner

jubatus/server/framework/save_load.cpp, jubatus/server/framework/server_base.cpp
=> fix parameter validation location of save/load RPC (fix #1038)

config/clustering/gmm.json, config/clustering/kmeans.json, config/clustering/kmeans_combinational_feature.json
Refs https://github.com/jubatus/jubatus_core/pull/180
=> add seed to clustering config examples

jubatus/client/anomaly_client.hpp, jubatus/client/anomaly_types.hpp, jubatus/client/bandit_client.hpp, jubatus/client/bandit_types.hpp, jubatus/client/burst_client.hpp, jubatus/client/burst_types.hpp, jubatus/client/classifier_client.hpp, jubatus/client/classifier_types.hpp, jubatus/client/clustering_client.hpp, jubatus/client/clustering_types.hpp, jubatus/client/graph_client.hpp, jubatus/client/graph_types.hpp, jubatus/client/nearest_neighbor_client.hpp, jubatus/client/nearest_neighbor_types.hpp, jubatus/client/recommender_client.hpp, jubatus/client/recommender_types.hpp, jubatus/client/regression_client.hpp, jubatus/client/regression_types.hpp, jubatus/client/stat_client.hpp, jubatus/client/stat_types.hpp
(refs #1042)
Sorry, I forgot about client in #1049.
I regenerated client.
=> (develop) Regenerate client

jubatus/client/nearest_neighbor_client.hpp, jubatus/client/nearest_neighbor_types.hpp, jubatus/server/server/nearest_neighbor_impl.cpp, jubatus/server/server/nearest_neighbor_proxy.cpp, jubatus/server/server/nearest_neighbor_types.hpp
Regenerate NN server/client, refs #1051.
=> (develop) regenerate for #1051

tools/packaging/rpm/rpmbuild/jubadump/SPECS/jubadump.spec.in, tools/packaging/rpm/rpmbuild/jubatus/SPECS/jubatus.spec.in, tools/packaging/rpm/rpmbuild/log4cxx/SPECS/log4cxx.spec.in
=> Fix RPM package related errors

jubatus/server/server/recommender_serv.cpp
Refs https://github.com/jubatus/jubatus_core/pull/208
=> fix typo: similality should be similarity (in server)

jubatus/server/server/wscript
It is better to avoid listing the same thing in multiple places.
=> improve jubatus/server/server/wscript

config/recommender/lsh_unlearn_lru.json
Please merge after https://github.com/jubatus/jubatus_core/pull/190
=> Add an example config about lsh with unlearner

man/en/jenerator.1, man/ja/jenerator.1
Refs https://github.com/jubatus/website/pull/232
=> regenerated jenerator manpages

jubatus/server/common/signals.cpp, jubatus/server/common/system.cpp, jubatus/server/common/zk.cpp, tools/jenerator/src/cpp.ml
=> fix typo in messages (fix #1068)

config/anomaly/lof_inverted_index_euclid.json, config/recommender/inverted_index_euclid.json
Example configuration files for https://github.com/jubatus/jubatus_core/pull/127
=> add inverted_index_euclid example config files

config/recommender/minhash_unlearn_lru.json
Related https://github.com/jubatus/jubatus_core/pull/220
=> Add sample config of minhash using unlearner

jubatus/server/framework/server_util.cpp
=> Not re-configure logger when log_config is not specified

config/recommender/inverted_index_euclid_unlearn_lru.json
Related https://github.com/jubatus/jubatus_core/pull/237
=> Add sample config of inverted_index_euclid using unlearner

tools/packaging/allinone/README.md, tools/packaging/allinone/metadata/debian/control
Fix https://github.com/jubatus/jubatus/issues/1082
=> fix email address (refs #1082)

plugin/src/fv_converter/mecab_splitter.cpp, plugin/src/fv_converter/mecab_splitter.hpp, plugin/src/fv_converter/mecab_splitter_test.cpp
Fix #1073.
This patch depends on https://github.com/jubatus/jubatus_core/pull/256
=> implement options to mecab plugin that extracts specific part-of-speech (fix #1073)

jubatus/server/cmd/jubactl.cpp, jubatus/server/common/crc32.hpp, jubatus/server/framework/mixer/push_mixer_test_util.hpp
=> fix code style

jubatus/server/common/logger/logger.cpp, jubatus/server/common/logger/logger.hpp, jubatus/server/common/system.cpp, wscript
This is freebsd support patch. I make on FreeBSD 9.
=> freebsd support

config/recommender/euclid_lsh_unlearn_lru.json
Related https://github.com/jubatus/jubatus_core/pull/264
=> Add sample config of euclid_lsh using unlearner

config/nearest_neighbor/lsh_multithread.json
PR related to jubatus/jubatus_core#260
=> add sample config for parameter 'threads' (Nearest Neighbor)

config/classifier/cosine.json, config/classifier/euclidean.json
related to jubatus/jubatus_core#234
=> add classifier config sample

config/weight/default.json, jubatus/client/weight_client.hpp, jubatus/client/weight_types.hpp, jubatus/server/server/weight.idl, jubatus/server/server/weight_impl.cpp, jubatus/server/server/weight_proxy.cpp, jubatus/server/server/weight_serv.cpp, jubatus/server/server/weight_serv.hpp, jubatus/server/server/weight_types.hpp, wscript
This implements a feature to test fv_converter behavior (#1105)
=> add weight engine (#1105)

jubatus/server/framework/server_base.cpp, jubatus/server/framework/server_base.hpp
=> Add exclusive lock to save/load status

wscript
=> revert check_cxx(lib = 'dl') in wscript (fix #1121, refs #1099)

config/anomaly/lof_unlearner_lru.json
Add example config for https://github.com/jubatus/jubatus_core/issues/231, https://github.com/jubatus/jubatus_core/issues/292
=> add example config for anomaly LOF with unlearner

config/anomaly/lof.json, config/anomaly/lof_unlearner_lru.json, config/recommender/euclid_lsh.json, config/recommender/euclid_lsh_unlearn_lru.json, jubatus/server/server/anomaly.idl
Refs https://github.com/jubatus/jubatus_core/pull/265
=> (develop) Remove retain_projection in example config files and IDL

jubatus/client.hpp
=> fix missing weight_client.hpp in client.hpp (fix #1127)

README.rst
Fix #1126
(contents copied from http://jubat.us/en/quickstart.html)
=> fix readme (fix #1126)

jubatus/server/server/weight_serv.cpp
=> fix jubaweight to print log on startup (fix #1131)

.travis.yml, tools/packaging/allinone/jubapkg, tools/packaging/rpm/rpmbuild/mecab-ipadic/SPECS/mecab-ipadic.spec.in, tools/packaging/rpm/rpmbuild/mecab/SPECS/mecab.spec.in, tools/packaging/rpm/rpmbuild/ux/SPECS/ux.spec.in
=> escape from Google Code (fix #980)

jubatus/server/framework/server_util.cpp
=> Changed behavior when cannot reopen zk logfile

Dockerfile
* Update base image to Ubuntu 14.04.
* Add ``MAINTAINER`` instruction.
=> update Dockerfile to use Ubuntu 14.04

jubatus/server/server/regression_serv.cpp
related to https://github.com/jubatus/jubatus_core/pull/320
=> remove unnecessary argument in regression driver

jubatus/client/clustering_client.hpp, jubatus/client/clustering_types.hpp, jubatus/server/server/clustering.idl, jubatus/server/server/clustering_impl.cpp, jubatus/server/server/clustering_proxy.cpp, jubatus/server/server/clustering_serv.cpp, jubatus/server/server/clustering_serv.hpp, jubatus/server/server/clustering_types.hpp
related to jubatus/jubatus_core#317
=> refactoring clustering api

jubatus/server/common/cached_zk.cpp, jubatus/server/common/cached_zk.hpp, jubatus/server/common/cached_zk_test.cpp, jubatus/server/common/lock_service.hpp, jubatus/server/common/zk.cpp, jubatus/server/common/zk.hpp, jubatus/server/common/zk_test.cpp, jubatus/server/framework/mixer/push_mixer_test_util.hpp
Fixes https://github.com/jubatus/jubatus/issues/1145.
I removed unused method (``lock_service#hd_list``).
In addition, I fixed typo in test pattern name in this PR.
=> Fix zktest

jubatus/server/server/classifier_serv.cpp, jubatus/server/server/regression_serv.cpp
=> use same storage class for standalone and distributed mode (fix #469)

jubatus/server/fv_converter/so_factory_test.cpp
Fixed binary test to follow jubatus/jubatus_core#329
=> fix binary fv converter test

client_test/clustering_test.cpp
fix clustering test to follow jubatus/jubatus#1155, jubatus/jubatus#1159, jubatus/jubatus_core#334
=> fix clustering client test

.travis.yml
=> add --enable-opencv to travis config

config/clustering/dbscan.json, config/clustering/default.json, config/clustering/gmm.json, config/clustering/kmeans.json, config/clustering/kmeans_combinational_feature.json, jubatus/server/server/clustering_serv.cpp
I have modified the clustering server to follow jubatus/jubatus_core#334.
=> Modify clustering server config structure

config/regression/default.json, config/regression/pa.json, config/regression/pa_combinational_feature.json
I have fixed PA method to follow the change in jubatus/jubatus_core#327.
=> Fix PA method

plugin/src/fv_converter/image_feature.cpp, plugin/src/fv_converter/wscript
Need to require ``2.3.0`` instead of ``2.0.0``.
=> Fix OpenCV version requirements

client_test/clustering_test.cpp
related to #1161 
I have added get_nearest_members_light test to client_test
=> add get_nearest_members_light test

man/en/jubaconv.1, man/en/jubatus_proxy.8, man/en/jubatus_server.8, man/ja/jubaconv.1, man/ja/jubatus_proxy.8, man/ja/jubatus_server.8
https://github.com/jubatus/website/pull/309
=> Regenerate manpages

plugin/src/fv_converter/image_feature.cpp, plugin/src/fv_converter/image_feature.hpp, plugin/src/fv_converter/image_feature_opencv.hpp, plugin/src/fv_converter/image_feature_test.cpp, plugin/src/fv_converter/wscript
=> support opencv 2.0 for RHEL 6

README.rst, tools/packaging/allinone/jubapkg, tools/packaging/allinone/metadata/debian/control
This PR improves the DEB packaging tool to support Ubuntu 16.04.
refs https://github.com/jubatus/jubatus/issues/1180
=> Support DEB packaging for Ubuntu 16.04

tools/packaging/allinone/README.md, tools/packaging/allinone/docker/Dockerfile.ubuntu12, tools/packaging/allinone/docker/Dockerfile.ubuntu14, tools/packaging/allinone/docker/Dockerfile.ubuntu16
To automate DEB package build we need this.
=> add Dockerfiles to build all-in-one DEB package in Docker

README.rst
Refs https://github.com/jubatus/website/issues/323
=> deprecate support for Ubuntu 12.04 LTS

jubatus/server/framework/server_base.cpp, jubatus/server/framework/server_base.hpp, jubatus/server/framework/server_base_test.cpp, jubatus/server/framework/wscript
Fix https://github.com/jubatus/jubatus/issues/1188
=> validate save/load RPC argument

tools/packaging/rpm/rpmbuild/jubatus-core/SPECS/jubatus-core.spec.in, tools/packaging/rpm/rpmbuild/jubatus/SPECS/jubatus.spec.el6.in, tools/packaging/rpm/rpmbuild/jubatus/SPECS/jubatus.spec.el7.in
=> remove waf bug workaround (fix #1195)

plugin/src/fv_converter/image_feature.cpp
=> Fix the output of ORB

jubatus/server/server/anomaly_serv.cpp
Fixes #1194 
This patch should be merged after https://github.com/jubatus/jubatus_core/pull/372.
=> Improve get_status of anomaly

config/regression/arow.json, config/regression/cosine.json, config/regression/cw.json, config/regression/euclidean.json, config/regression/nherd.json, config/regression/nn.json, config/regression/pa1.json, config/regression/pa2.json
This PR fixes #1206 .
I tested these configs using `jubaregression` command.
=> Add regression configs

jubatus/client/anomaly_client.hpp, jubatus/client/anomaly_types.hpp, jubatus/client/bandit_client.hpp, jubatus/client/bandit_types.hpp, jubatus/client/burst_client.hpp, jubatus/client/burst_types.hpp, jubatus/client/classifier_client.hpp, jubatus/client/classifier_types.hpp, jubatus/client/clustering_client.hpp, jubatus/client/clustering_types.hpp, jubatus/client/graph_client.hpp, jubatus/client/graph_types.hpp, jubatus/client/nearest_neighbor_client.hpp, jubatus/client/nearest_neighbor_types.hpp, jubatus/client/recommender_client.hpp, jubatus/client/recommender_types.hpp, jubatus/client/regression_client.hpp, jubatus/client/regression_types.hpp, jubatus/client/stat_client.hpp, jubatus/client/stat_types.hpp, jubatus/client/weight_client.hpp, jubatus/client/weight_types.hpp
=> Regenerate clients

tools/jenerator/src/go.ml
Fixes https://github.com/jubatus/jubatus-go-client/issues/7
=> Use unsigned integer types in Go-lang client generator

tools/packaging/allinone/metadata/debian_ubuntu14/control, tools/packaging/allinone/metadata/debian_ubuntu16/control
=> Add dependency of a deb package to fix opencv error

.travis.yml
sed: #1217, https://travis-ci.org/jubatus/jubatus/builds/292008983
=> travis-ci: Fix opencv error and optimized clone performance

config/clustering/kmeans.json, jubatus/server/server/clustering_serv.cpp
related to jubatus/jubatus_core#396
Fix jubaclustering server to accept distance option.
=> add distance option to clustering

tools/jenerator/test/test.sh
Related https://github.com/jubatus/jubatus/pull/1231
=> Fix jenerator's test in Ubuntu18.04

tools/packaging/allinone/jubapkg
See. https://github.com/jubatus/jubatus-installer/pull/57
=> specify libdir when configuring jubatus, jubatus_core and jubadump in packaging tool
