jubatus/jubatus

- jubatus/server/common/zk.cpp
Fixed #911.
zoo_get_children() returns allocated memory implicitly.
> Fix memory leak.

- jubatus/server/fv_converter/dynamic_combination_feature.cpp
- jubatus/server/fv_converter/dynamic_combination_feature.hpp
- jubatus/server/fv_converter/so_factory.cpp
- jubatus/server/fv_converter/so_factory.hpp
- jubatus/server/fv_converter/wscript
- jubatus/server/server/nearest_neighbor_serv.cpp
CI will fail because `jubatus_core`'s so_file.hpp force to inherit `combination_feature()` function.
`combination_feature` is newly supported via issue [104](https://github.com/jubatus/jubatus_core/pull/104)
> support combination feature

- jubatus/server/wscript
- wscript
I am intentionally sending this pull-req to master branch, as it strongly impacts the operation of CI server.
Most Linux systems use port range of 32768-61000 for ephemeral (source) ports.
This may possible cause `address in use` error, so we should avoid using them for tests.
This also fixes #922.
> fix RPC port range used for test

- tools/jenerator/test/test.sh
Current jenerator test fails as dependency to `jubatus_core` is not specified.
```
/usr/bin/ld: /tmp/ccvE5HEb.o: undefined reference to symbol 'jubatus::core::common::exception::jubatus_exception::diagnostic_information(bool) const'
/usr/bin/ld: note: 'jubatus::core::common::exception::jubatus_exception::diagnostic_information(bool) const' is defined in DSO /opt/jubatus/lib/libjubatus_core.so.0 so try adding it to the linker command line
/opt/jubatus/lib/libjubatus_core.so.0: could not read symbols: Invalid operation
```
> add jubatus_core dependency to jenerator test

- jubatus/server/framework/proxy.hpp
- jubatus/server/framework/proxy_common.cpp
- jubatus/server/framework/proxy_common.hpp
fix issue #757 
On broadcasting RPC, master lock of jubatus cluster should be required for avoiding to interleave of broadcasting and MIX.
> generation management of clear and load

- jubatus/server/framework/mixer/linear_mixer.cpp
`get_status` function only does reads two atomic variable.
the atomicity of these two values are not important.
remove lock. fix #912
> do not lock mixer on `get_status()`

- tools/jenerator/.gitignore
- tools/jenerator/src/OMakefile
- tools/jenerator/src/syntax.ml
- tools/jenerator/test/OMakefile
- tools/jenerator/test/parse_test.ml
- add `result` type and extract `parse` method
- add successful test
- add `*.cmo` and `oUnit-anon.cache` to gitignore
- add `ppx_deriving` to test printer
- see https://github.com/whitequark/ppx_deriving
- Ocaml >= 4.02.0
- `ppx_deriving` library(`opam install ppx_deriving`)
> [jenerator]refactor parse test

- jubatus/server/framework/mixer/linear_mixer.cpp
`linear_mixer::mix()` fails when all `get_diff`s fail.
It is meaningless to call `put_diff` when all `get_diff`s fail, so I modified `linear_mixer::mix()` not to call `put_diff`s.
> Prevent SEGV in mix.

- jubatus/server/common/lock_service.hpp
- jubatus/server/common/zk.cpp
- jubatus/server/common/zk.hpp
- jubatus/server/framework/mixer/push_mixer_test.cpp
- jubatus/server/framework/server_util.cpp
This fixes #876; now ZK logs can be rotated by external tools like logrotate.
> reopen ZK log files on SIGHUP signal (fix #876)

- wscript
> Stop printing verbose log from cpplint.

- jubatus/server/server/nearest_neighbor_serv.hpp
`table::column` is mistakenly used...
> (develop) use storage::column instead of table::column

- jubatus/server/server/nearest_neighbor_serv.cpp
- jubatus/server/server/nearest_neighbor_serv.hpp
This patch fixes #883.
* Currently, build_cnt, clear_row_cnt, mix_cnt are unused and uninitialized.
I removed these values.
* Currently, update_row_cnt is *used* but uninitialized.
I fixed the value to initialize with 0.
> clean up nearest_neighbor status values (fix #883)

- jubatus/server/framework/server_util.hpp
related issue: https://github.com/jubatus/jubatus/issues/982
> Fix run_server to use std::cerr when logger is not configured

- jubatus/server/fv_converter/dynamic_combination_feature.cpp
- jubatus/server/fv_converter/dynamic_combination_feature.hpp
Support non-commutative combination functions in plug-ins.
This patch must be merged after https://github.com/jubatus/jubatus_core/pull/156.
> support non-commutative functions in combination feature

- jubatus/server/server/wscript
- wscript
Fix #1009.
I moved the engine list to the root wscript. I intend to use `JUBATUS_ENGINES` variable in `man/wscript` in the next patch.
> fix nearest_neighbor.idl not installed (fix #1009)

- jubatus/server/framework/mixer/push_mixer.cpp
> Removed scoped_lock in push, pull, get_pull_argument

- tools/packaging/rpm/rpmbuild/jubatus-core/SPECS/jubatus-core.spec.in
- tools/packaging/rpm/rpmbuild/jubatus/SPECS/jubatus.spec.in
Currently jubatus-core-debuginfo and jubatus-debuginfo RPM packages does not provide complete debug information, as pointed in #970.
As a workaround until we migrate to the newer version of waf, add execution permission manually in SPEC file.
> workaround debuginfo issue (refs #970)

- tools/jenerator/src/go.ml
* Change ``save`` RPC signature.
* Fix ``get_config`` method signature.
* Add missing ``get_status`` & ``get_proxy_status`` methods.
> fix go client RPC interface

- jubatus/server/framework/mixer/linear_mixer.cpp
I added the following values to get_status of linear_mixer.
* ``linear_mixer.is_obsolete``
* ``linear_mixer.is_running``
Next, we should add these to push_mixer.
> Add status info to linear_mixer

- plugin/src/fv_converter/mecab_splitter.cpp
- plugin/src/fv_converter/mecab_splitter_test.cpp
- plugin/src/fv_converter/ux_splitter.cpp
Prior to https://github.com/jubatus/jubatus/pull/1025, `plugin` directory was not checked against cpplint.
This fixes cpplint violations in plugins.
> fix cpplint in plugins

- jubatus/server/common/cached_zk.cpp
Should not create the cache when failed to register the watcher to ZooKeeper.
Fixed #1035
> Fix conditions that create the cache of node list

- tools/packaging/allinone/jubapkg
- tools/packaging/rpm/rpmbuild/ux/SPECS/ux.spec.in
Escape from Google Code, partially fixes #980
Note: mecab and mecab-ipadic is not included in this patch, as currently they don't have tags in their Git repos. https://github.com/taku910/mecab/issues/20
> escape from google code (ux-trie)

- tools/jenerator/src/cpp.ml
- tools/jenerator/src/syntax.ml
- tools/jenerator/test/sample.idl
Fixes #1022
> I believe add is unnecessary in aggregators.hpp.
On second thought,  I added ``add`` to ``jenerator``.
Because, we might use ``add`` someday.
> Add aggregate-type "add" to jenerator

- jubatus/server/server/clustering_serv.cpp
Currently, identifier of clustering engine is generated in format of ``IP`` + ``PORT``.
This may cause a conflict of ID in the Jubatus cluster, e.g., (IP: ``10.0.0.11``, Port: ``9199``) and (IP: ``10.0.0.1``, Port: ``19199``) both generate ID ``10.0.0.119199``.
Confliction of ID cause MIX to work improperly.
This patch fixes the problem by inserting ``_`` between IP and Port.
This is slightly related to https://github.com/jubatus/jubatus_core/issues/70.
> Avoid clustering identifier conflict

- client_test/.gitignore
- client_test/README.md
- client_test/clustering_test.cpp
- client_test/envdef.sample.py
- client_test/test_gtest.py
- client_test/util.hpp
Fix #1019.
* Fix clustering test conditions so that clustering batch runs.
* Remove distributed mode test, as these tests are not intended for integration tests.  Instead, we should write integration tests in [jubatest-cases](https://github.com/kmaehashi/jubatest-cases).
* Add envdef.sample.py along with updated README to easily run tests.
* Improve environment variable handling for better output.
> Fix C++ client test conditions (fix #1019)

- Dockerfile
If jabatus published a public base image, this would help newbies very efficiently.
This just performs:
* based on ubuntu 12.04 LTS 64bit (ubuntu:12.04)
* install the latest jabatus
* set required environment variables from /opt/jubatus/profile
_CAUTION: Because I'm not sure who is an appropriate maintainer, this Dockerfile doesn't include MAINTAINER clause. Jubatus committer could add the clause later._
> Dockerfile for jabatus base image.

- tools/packaging/allinone/jubapkg
- tools/packaging/rpm/rpmbuild/oniguruma/SPECS/oniguruma.spec.in
Fix #1045
As this fix is needed to create build environment of CI server, I intentionally point this PR to master branch.  Need to manually merge this into develop later.
> fix oniguruma source URL (fix #1045)

- jubatus/server/framework/server_base.cpp
Fix #1055, now models can be loaded via command line option.
This was a regression introduced in v0.8.2 via #1039.
> fix load model parameter validation (fix #1055)

- jubatus/server/server/nearest_neighbor.idl
With [jubatus_core#188](https://github.com/jubatus/jubatus_core/pull/188), `nearest_neighbor` is now thread safe so that shared lock of these methods can be eliminated.
> nearest_neighbor can be drived with `nolock`

- client_test/test_gtest.py
Fix #1043
You need to use develop branch of [jubatest](https://github.com/kmaehashi/jubatest/) (in develop branch) to run with Python 3.x.
> fix client_test to work with Python 3.x (fix #1043)

- plugin/src/fv_converter/mecab_splitter.cpp
- plugin/src/fv_converter/mecab_splitter.hpp
- plugin/src/fv_converter/mecab_splitter_test.cpp
This PR implements feature proposed in #1054.
I added `"ngram"` configuration option to the MeCab plugin.  Example config file is as follows:
```json
{
"converter" : {
"string_filter_types" : {},
"string_filter_rules" : [],
"num_filter_types" : {},
"num_filter_rules" : [],
"string_types" : {
"bigram": {"method": "ngram", "char_num": "2"},
"mecab": {
"method": "dynamic",
"path": "libmecab_splitter.so",
"function": "create",
"ngram": "2"
}
},
"string_rules" : [
{ "key" : "bigram", "type" : "bigram", "sample_weight" : "bin", "global_weight" : "bin" },
{ "key" : "mecab", "type" : "mecab", "sample_weight" : "bin", "global_weight" : "bin" }
],
"num_types" : {},
"num_rules" : []
},
"method" : "perceptron"
}
```
When `1 < ngram` is specified, morpheme n-gram features are generated.
For example, …
> support morpheme n-gram in mecab plugin (fix #1054)

- jubatus/server/jubavisor/main.cpp
The same fix as #1084 is needed for jubavisor, too.
Fix #962
> do not reconfigure default logger (fix #962, refs #1084)

- jubatus/server/framework/save_load.cpp
> compare config semantically instead of naive string match when loading model (fix #1080)

- plugin/src/fv_converter/mecab_splitter.cpp
- plugin/src/fv_converter/mecab_splitter.hpp
- plugin/src/fv_converter/mecab_splitter_test.cpp
This patch implements #1074; fix `mecab_splitter` to support extracting base form (原形) of words.
* A new plugin parameter `"base"` (boolean) is added, which defaults to false.
* For words without base form (e.g. proper nouns (固有名詞)), the surface is used instead.
> fix mecab_splitter to support extracting base form

- jubatus/server/cmd/jubactl.cpp
`jubactl -c save` subcommand aborts with `msgpack::type_error` constantly. Example:
$ jubactl -c save --server jubarecommender --type recommender --name similarticle --zookeeper zk1:2181 --thread 4 --datadir /var/lib/jubatus/
2016-03-15 23:34:54,753 2442 INFO  [zk.cpp:644] got ZooKeeper event: type SESSION_EVENT(-1), state CONNECTED_STATE(3)
2016-03-15 23:34:54,753 2442 INFO  [zk.cpp:655] ZooKeeper session established: connected to 10.140.0.4:2181, negotiated timeout 10000 ms
sending save / similarticle to 10.140.0.3_9199...terminate called after throwing an instance of 'msgpack::type_error'
what():  std::bad_cast
Aborted (core dumped)
The cause of the error is that jubactl wrongly expects a bool result from `save` RPC call, although it returns a map<string, string> actually.
This pull …
> Fixes "jubactl -c save" subcommand which is not working

- jubatus/server/framework/proxy.hpp
This patch fixes #1048 
```
2016-03-16 15:44:33,808 4489 WARN  [proxy.hpp:425] request timeout occurred: xxx.xx.xxx.xx:9111
```
> Add log message when fowarded request is timed out

- tools/jenerator/test/test.sh
Test fails on Ubuntu 14.04 without `-pthread`
> add -pthread to jenerator test script

- jubatus/server/framework/save_load.cpp
- jubatus/server/framework/save_load.hpp
- jubatus/server/framework/server_base.cpp
- jubatus/server/framework/server_helper.hpp
- jubatus/server/framework/server_util.cpp
Fixes #1081.
In standalone, if a model file is specifed on startup, use the configuration from the model file.
When both a model file and a config file is specified, the config file is ignored (and INFO log to notify that to user is printed).
This fix does not affect distributed mode.
In distributed mode, you cannot specify a model file on startup.
> use config in model file (fix #1081)

- tools/codestyle/run_cpplint.sh
Now `./waf cpplint` checks include guard.
Refs https://github.com/jubatus/jubatus_core/pull/293
> add include guard check to run_cpplit (server)

- jubatus/server/framework/mixer/linear_mixer.cpp
Fixes #1093 
I changed to be the  same as ``push_mixer``.
https://github.com/jubatus/jubatus/blob/0.9.2/jubatus/server/framework/mixer/push_mixer.cpp#L293
> Add missing lock in get_status

- wscript
> disable _GLIBCXX_DEBUG when configured with --enable-debug (fix #910)

- tools/packaging/rpm/package-config
- tools/packaging/rpm/package-prebuild
- tools/packaging/rpm/package.sh
- tools/packaging/rpm/rpmbuild/mecab-ipadic/SPECS/mecab-ipadic.spec.in
- tools/packaging/rpm/rpmbuild/mecab/SPECS/mecab.spec.in
On RHEL 6, `spectool`, which is a tool to download sources used to build RPM packages, does not handle Google Drive URLs correctly.  More precisely:
* It cannot well-handle URLs like ``http:// ... /#/source-0.1.tar.gz``.  The hash part is completely ignored.
* It expects HTTP server that distributes tarball to support time stamping (to check if local copy of tarball is still up-to-date or not.) It seems that Google Drive HTTP servers does not support time stamping, causing ``HTTP 503: Service Unavailable`` error response.
This PR workarounds the problem by avoid using ``spectool``.
> Fix handling of Google Drive URLs in packaging tools

- wscript
Fix #1138 
In addition, I tested jubatus (build with ``_GLIBCXX_DEBUG``) using ``waf --checkall``.
> Add a note about ux-trie when build with _GLIBCXX_DEBUG

- jubatus/server/framework/server_util.cpp
Fix #891.
To workaround the log4cxx crash bug described in the above issue, we check that log4cxx config file is not empty (has at least one token) in the specified config file.
> fix to validate if log4cxx config file is not empty (fix #891)

- jubatus/server/common/logger/logger.hpp
Fix #947.  This PR changes the logging system to print ``DEBUG`` level logs by defualt, even without configured with ``--enable-debug``.
For example, when similar_row_from_id RPC of NN is called:
```
2016-08-23 16:56:14,732 9901 DEBUG [nearest_neighbor_serv.cpp:159] similar_row_from_id
```
Notes:
* To turn off the DEBUG level logs you need to specify log configuration file.
* You can grep the jubatus source by ``DLOG`` to see what kind of debug logs are currently available.
* Currently TRACE level logs are unused.
> print debug log by default (fix #947)

- jubatus/server/cmd/jubaconfig.cpp
- jubatus/server/cmd/jubactl.cpp
- jubatus/server/framework/server_util.cpp
- jubatus/server/jubavisor/main.cpp
Fix #1078.  Jubatus logger now use locale declared in the environment variable.
Jubatus processes (servers, proxies and commands) now explicitly set ``LC_ALL`` by the following code:
```
setlocale(LC_ALL, "");
```
... as documented in https://svn.apache.org/repos/asf/logging/site/trunk/docs/log4cxx/faq.html#unicode:
>  Applications should call setlocale(LC_ALL, "") on startup or the C RTL will assume US-ASCII.
c.f. https://linuxjm.osdn.jp/html/LDP_man-pages/man3/setlocale.3.html
```
$ jubaclassifier -f テスト.json
2016-08-18 11:02:50,947 10135 FATAL [server_util.hpp:146] exception in main thread: Dynamic exception type: jubatus::core::common::exception::runtime_error::what: Failed to get realpath
#0 [jubatus::core::common::exception::error_api_func_*] = realpath
#0 …
```
> support printing non-ASCII characters in logs (fix #1078)

- jubatus/server/common/mprpc/exception.hpp
- jubatus/server/common/mprpc/rpc_error.hpp
This PR fixes to use new macro ``DEFINE_ERROR_TAG`` instead of directly specializing ``error_info`` via typedef to define error tags.
Needs to be merged once https://github.com/jubatus/jubatus_core/pull/313 got merged.
> use new macro to define error tags

- jubatus/server/common/unique_lock.hpp
- jubatus/server/common/unique_lock_test.cpp
- jubatus/server/framework/mixer/linear_mixer.cpp
- jubatus/server/framework/mixer/linear_mixer.hpp
- jubatus/server/framework/mixer/push_mixer.cpp
- jubatus/server/framework/mixer/push_mixer.hpp
~~Fixes #1092~~
In mixer, two mutexes are implemented. But they are not used correctly.
For example, ``m_`` in ``linear_mixer`` should be used to protect status values (`counter_`, `ticktime_`, `is_running_`, `is_obsolete_`) by read/write operation. But ``is_obsolete`` in ``update_model`` is not protected by ``m_`` in the write operation.
https://github.com/jubatus/jubatus/blob/0.9.3/jubatus/server/framework/mixer/linear_mixer.cpp#L593
I reviewed and fixed the exclusive controls in MIX as two mutexes are used correctly.
In addition, I tested with the following test:
https://github.com/rimms/misc/tree/master/monkey-mix
``liner_mixer`` and ``broadcast_mixer`` passed 3 times test.
~~I'm trying to implement this in``push_mixer`` .~~
> Reconsider the exclusive controls in MIX

- jubatus/server/framework/proxy_common.cpp
- jubatus/server/framework/server_helper.cpp
- jubatus/server/framework/server_util.cpp
- jubatus/server/framework/server_util.hpp
Fix #1072.
When ``--daemon`` option is specified, it detaches from console immediately.
> fix --daemon option to detach from console (fix #1072)

- jubatus/server/common/logger/logger.cpp
- log4cxx.xml
DLOGs are frequently used: e.g.  https://github.com/jubatus/jubatus/blob/master/jubatus/server/server/classifier_serv.cpp#L142
To improver performance disable DEBUG logs when not explicitly specified.
> Fix default log level to INFO when --log_config is not specified

- plugin/src/fv_converter/image_feature.cpp
- plugin/src/fv_converter/image_feature_test.cpp
I have modified the test of image feature extractors as follows.
- modify the test of ORB algorithm  
In this plugin, default parameter of ORB is used, which is changed with version of OpenCV. Therefore I modified the test to be independent of the version of OpenCV.  
- add the test of dense sampling  
I added the test of "dense sampling" which is newly implemented in this plugin.
> Modify the test of image feature plugin

- jubatus/server/framework/server_base.hpp
- jubatus/server/server/graph_serv.cpp
- jubatus/server/server/graph_serv.hpp
Fix #1149
This must be merged after https://github.com/jubatus/jubatus_core/pull/333
> fast-forward global ID generator in graph engine (fix #1149)

- jubatus/server/framework/server_util.cpp
- jubatus/server/framework/server_util.hpp
- jubatus/server/server/anomaly_impl.cpp
- jubatus/server/server/bandit_impl.cpp
- jubatus/server/server/burst_impl.cpp
- jubatus/server/server/classifier_impl.cpp
- jubatus/server/server/clustering_impl.cpp
- jubatus/server/server/graph_impl.cpp
- jubatus/server/server/nearest_neighbor_impl.cpp
- jubatus/server/server/recommender_impl.cpp
- jubatus/server/server/regression_impl.cpp
- jubatus/server/server/stat_impl.cpp
- jubatus/server/server/weight_impl.cpp
- tools/jenerator/src/cpp.ml
Fix #973.
Add ``--config_test, -T`` option to jubatus server.
By using this option, configurations can be tested without running RPC server.
If the config is OK, the server will exit with status 0; otherwise exit with 1.
Valid config:
```
$ jubaclassifier --config_test -f config/classifier/pa.json
2016-08-24 19:00:54,292 12550 INFO  [server_util.cpp:416] starting jubaclassifier 0.9.3 RPC server at 192.168.122.211:9199
pid                  : 12550
user                 : jubatus
mode                 : standalone mode
timeout              : 10
thread               : 2
datadir              : /tmp
logdir               : 
log config           : 
zookeeper            : 
name                 : 
interval sec         : 16
interval count       : 512
zookeeper timeout    : 10
interconnect timeout : …
```
> Add config validation feature (fix #973)

- tools/packaging/allinone/README.md
- tools/packaging/allinone/jubapkg
- tools/packaging/allinone/metadata/debian/control
- tools/packaging/allinone/metadata/jubatus-allinone.spec
- tools/packaging/rpm/README.rst
- tools/packaging/rpm/package-prebuild
- tools/packaging/rpm/rpmbuild/jubatus/SPECS/jubatus.spec.el6.in
- tools/packaging/rpm/rpmbuild/jubatus/SPECS/jubatus.spec.el7.in
Refs #1150.
This introduces 2 changes:
* DEB package: now depends on OpenCV library.
* RPM package: separate plugins from main ``jubatus`` package.
Users can now choose which plugins to be installed.
----
* Merge after #1150.  I'm still testing this PR in several systems.
* Need to update docs. (installation procedure)
> update packaging tools to support image feature extraction

- Dockerfile
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/
> Minimize the number of layers
> In addition, cleaning up the apt cache and removing /var/lib/apt/lists helps keep the image size down. Since the RUN statement starts with apt-get update, the package cache will always be refreshed prior to apt-get install.
After applying this patch the image size reduced from 365.2 MB to 343 MB.
> clean up after installation and reduce number of layers

- jubatus/server/framework/save_load.cpp
Fix #1179.
When loading old model, the following error message is displayed:
```
2017-03-21 11:55:25,433 20764 INFO  [server_base.cpp:60] starting load from /tmp/192.168.122.211_9199_classifier_foo.jubatus
2017-03-21 11:55:25,433 20764 FATAL [server_util.hpp:161] exception in main thread: jubatus::core::common::exception::runtime_error: cannot load model file created before v1.0.0: 0.8.9
(#0) Source: ../jubatus/server/framework/save_load.cpp
(#0) Line: 192
(#0) Function: void jubatus::server::framework::load_server(std::istream&, jubatus::server::framework::server_base&, const string&, bool)
```
> Disable strict version checking (fix #1179)

- README.rst
please see [here](https://github.com/kumagi/jubatus/blob/show-build-status-of-travis/README.rst).
Build status badge is good indicator of OSS. How about add it?
> Show build status of travis-ci in README.rst

- jubatus/server/server/classifier_serv.cpp
- jubatus/server/server/regression_serv.cpp
This reverts commit 26362610725c42190b7dbcd2fb3377d467424fee. Refs #1190
> Revert "use same storage class for standalone and distributed mode (fix #469)"

- jubatus/server/framework/save_load.cpp
Semantic comparision of config, which runs when loading a model to already-running server, was not working stably.
As `jubatus::util::text::json` is implemented using `unordered_map`, the serialized JSON string is not always the same for the same JSON data structure.
This PR fixes the issue by comparing config with `==` operator, which was introduced in https://github.com/jubatus/jubatus_core/pull/380, instead of comparing serialized JSON config string.
This issue was found during review of https://github.com/jubatus/jubakit/pull/83.
> fix config comparision not working stably
